/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conexao.ConexaoBD;
import controle.controleusuario;
import controle.controltweets;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;
import modelo.Tweets;
import modelo.Usuario;


/**
 *
 * @author adao-
 */
public class telarelatorio extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    int flag = 0;
    Usuario usuario = new Usuario();
    Tweets status = new Tweets();
    controleusuario control = new controleusuario();
    controltweets control1 = new controltweets ();
    public telarelatorio() {
        initComponents();
       
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabjogador = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtabjogador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtabjogador);

        jLabel1.setText("RELATORIO");

        jLabel3.setText("Hashtag");

        jButton1.setText("Local");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nº HASHTAG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hashtag");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try {
            preencherTabelalocal("SELECT local, COUNT(local) FROM user GROUP BY local ORDER BY COUNT(local)desc ");
        } catch (SQLException ex) {
            Logger.getLogger(telarelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            preencherTabelahashtag("select hashtag,count(hashtag) from tweets GROUP BY hashtag ORDER BY COUNT(hashtag)desc");
        } catch (SQLException ex) {
            Logger.getLogger(telarelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            preencherTabela("select ScreenName,status,hashtag from user,tweets where codigo=codigouser and hashtag like '%"+jTextField3.getText()+"%'");
           // select *from equipe where nome_equipe like'%"+mod.getPesquisa()+"%'"
        } catch (SQLException ex) {
            Logger.getLogger(telarelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void preencherTabela(String sql) throws SQLException{
    ArrayList dados = new ArrayList();
    String [] colunas = new String  [] { "Nome","STATUS","hashtag"};
     conecta.conexao();
     conecta.execultaSql(sql);
     try{
     
     conecta.rs.first();
     do{
     dados.add(new Object [] {conecta.rs.getString("ScreenName"),conecta.rs.getString("status"),conecta.rs.getString("hashtag")});    
     }while(conecta.rs.next());
     }catch(SQLException ex){
     
     }
     ModeloTabela modelo = new ModeloTabela(dados,colunas);
     jtabjogador.setModel(modelo);
     jtabjogador.getColumnModel().getColumn(0).setPreferredWidth(100);
     jtabjogador.getColumnModel().getColumn(0).setResizable(false);
     jtabjogador.getColumnModel().getColumn(1).setPreferredWidth(600);
     jtabjogador.getColumnModel().getColumn(1).setResizable(false);
     jtabjogador.getColumnModel().getColumn(2).setPreferredWidth(100);
     jtabjogador.getColumnModel().getColumn(2).setResizable(false);
     
     
     jtabjogador.getTableHeader().setReorderingAllowed(false);
     jtabjogador.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
     jtabjogador.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
    }
    public void preencherTabelahashtag(String sql) throws SQLException{
    ArrayList dados = new ArrayList();
    String [] colunas = new String  [] { "HASHTAG","Tweets"};
     conecta.conexao();
     conecta.execultaSql(sql);
     try{
     
     conecta.rs.first();
     do{
      dados.add(new Object [] {conecta.rs.getString("hashtag"),conecta.rs.getString("count(hashtag)")});       
     }while(conecta.rs.next());
     }catch(SQLException ex){
     
     }
     ModeloTabela modelo = new ModeloTabela(dados,colunas);
     jtabjogador.setModel(modelo);
     jtabjogador.getColumnModel().getColumn(0).setPreferredWidth(100);
     jtabjogador.getColumnModel().getColumn(0).setResizable(false);
     jtabjogador.getColumnModel().getColumn(1).setPreferredWidth(600);
     jtabjogador.getColumnModel().getColumn(1).setResizable(false);
    
    
     
     jtabjogador.getTableHeader().setReorderingAllowed(false);
     jtabjogador.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
     jtabjogador.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
    }
    public void preencherTabelalocal(String sql) throws SQLException{
    ArrayList dados = new ArrayList();
    String [] colunas = new String  [] { "LOCAL","QUANTIDADE"};
     conecta.conexao();
     conecta.execultaSql(sql);
     try{
     
     conecta.rs.first();
     do{
      dados.add(new Object [] {conecta.rs.getString("local"),conecta.rs.getInt("COUNT(local)")});       
     }while(conecta.rs.next());
     }catch(SQLException ex){
     
     }
     ModeloTabela modelo = new ModeloTabela(dados,colunas);
     jtabjogador.setModel(modelo);
     jtabjogador.getColumnModel().getColumn(0).setPreferredWidth(100);
     jtabjogador.getColumnModel().getColumn(0).setResizable(false);
     jtabjogador.getColumnModel().getColumn(1).setPreferredWidth(600);
     jtabjogador.getColumnModel().getColumn(1).setResizable(false);

    
     
     jtabjogador.getTableHeader().setReorderingAllowed(false);
     jtabjogador.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
     jtabjogador.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telarelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telarelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telarelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telarelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telarelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jtabjogador;
    // End of variables declaration//GEN-END:variables
}
